### ISSUE TITLE
capistrano deployment?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/crez-sw-ingest#7]
https://jirasul.stanford.edu/jira/browse/INDEX-9

**Comment by cbeer** [comment]
Currently deployed manually to sw-solr-g and sw-solr-m (by ssh'ing to the box and cloning the repository)

**Comment by ndushay** [comment]
i apologize heartily for the many ways all of this indexing is a fustercluck.  It is, however, also a complex problem.  I look forward to learning all about how you can improve it mightily!
